version: "3.9"
services:
  web:
    build: .
    ports:
      - "8085:8085"
    links:
      - "logstash:logstash"
    depends_on:
      - "elasticsearch"
      - "kibana"
      - "logstash"    
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.14.1"
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "discovery.type=single-node"
  kibana:
    image: "kibana:7.14.1"
    ports:
      - "5601:5601"
    links:
      - "elasticsearch:elasticsearch"
    depends_on:
      - "elasticsearch"
  logstash:
    image: "logstash:7.14.1"
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    ports:
      - "5000:5000"
    links:
      - "elasticsearch:elasticsearch"
    volumes:
    - ./logstash.conf:/etc/logstash/conf.d/logstash.conf:ro    
    depends_on:
      - "elasticsearch"